### ISSUE TITLE
Error: unknown primitive "file" in /type

### ISSUE THREAD

**Issue by matt328** [Remco75/openapi-test-generator#2]
I was having trouble getting this to do anything with our own swagger.json files which are huge and complex.  Even with Swagger's own pet store example swagger.json, (http://petstore.swagger.io/v2/swagger.json) I get the following:

```
/Users/matt/Projects/git/angular-testarea/node_modules/json-schema-faker/lib/jsf.js:74
      throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
      ^

Error: unknown primitive "file" in /type
    at generate (/Users/matt/Projects/git/angular-testarea/node_modules/json-schema-faker/lib/jsf.js:74:13)
    at generate (/Users/matt/Projects/git/angular-testarea/node_modules/json-schema-test-data-generator/dist/index.js:439:20)
    at /Users/matt/Projects/git/angular-testarea/node_modules/open-api-test-generator/src/generateRequestMocks.js:37:98
    at Array.forEach (native)
    at generateRequestMock (/Users/matt/Projects/git/angular-testarea/node_modules/open-api-test-generator/src/generateRequestMocks.js:36:62)
    at /Users/matt/Projects/git/angular-testarea/node_modules/open-api-test-generator/src/index.js:25:82
    at Array.forEach (native)
    at Object.generate (/Users/matt/Projects/git/angular-testarea/node_modules/open-api-test-generator/src/index.js:23:19)
    at Object.<anonymous> (/Users/matt/Projects/git/angular-testarea/src/support/index.js:7:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```
I am calling it exactly as you are in your documentation:

```javascript
var OpenApiGenerator = require('open-api-test-generator');
var spec = require('./swagger.json');
var generator = OpenApiGenerator(spec, './mocks');
generator.generate();
```

**Comment by Remco75** [comment]
@matt328 , thnx for looking into the module. The error is somewhere in the generation dependencies. It fails on the invalid type: file in the petstore.json. I was hoping for a quick fix, but it will take some more time, sorry. Will get back asap.

**Comment by Remco75** [comment]
btw, you can test the module and see it working by changing the file type into something like string
