### ISSUE TITLE
unknown generator for "date" in /items/0/properties/StartDateTime

### ISSUE THREAD

**Issue by thangakumard** [Remco75/openapi-test-generator#3]
C:\user\Official\Projects\OpenAPITest>node index.js
C:\user\Official\Projects\OpenAPITest\node_modules\json-schema-faker\lib\jsf.js:74
      throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
      ^

Error: unknown generator for "date" in /items/0/properties/StartDateTime
    at generate (C:\user\Official\Projects\OpenAPITest\node_modules\json-schema-faker\lib\jsf.js:74:13)
    at generate (C:\user\Official\Projects\OpenAPITest\node_modules\json-schema-test-data-generator\dist\index.js:439:20)
    at C:\user\Official\Projects\OpenAPITest\node_modules\open-api-test-generator\src\generateRequestMocks.js:37:61
    at Array.forEach (native)
    at generateRequestMock (C:\user\Official\Projects\OpenAPITest\node_modules\open-api-test-generator\src\generateRequestMocks.js:36:62)
    at C:\user\Official\Projects\OpenAPITest\node_modules\open-api-test-generator\src\index.js:25:82
    at Array.forEach (native)
    at Object.generate (C:\user\Official\Projects\OpenAPITest\node_modules\open-api-test-generator\src\index.js:23:19)
    at Object.<anonymous> (C:\user\Official\Projects\OpenAPITest\index.js:10:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by Remco75** [comment]
Hi Thnx for the issue. this is actually an issue with a dependency that can't seem to handle a date (json-schema-test-data-generator). In order to fix this we need to reproduce the bug in the dep, and fix it there, release it, and use the updated dep here.
 At this point I am not really actively developing on this repo, (this might change in the neat future btw) so, if you want to investigate I am more than happy to accept PR's and merge them
