### ISSUE TITLE
OpenAPI spec Not valid

### ISSUE THREAD

**Issue by AakashMasand** [Remco75/openapi-test-generator#5]
Hi, I am using the API code to generate tests for my swagger doc written in OpenApi v3
Error: openAPI spec not valid
    at module.exports (/Users/akash/repos/stope-reconciliation-azure/Azure API/Tests/node_modules/open-api-test-generator/src/index.js:73:66)
    at Object.<anonymous> (/Users/akash/repos/stope-reconciliation-azure/Azure API/Tests/testgen.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by Remco75** [comment]
Hi, This repo was written against openApi spec 2. For validation of the spec we use swagger-schema-official , which seems kinda abandoned. In order to move on I should rewrite this module and use typescript with this module: https://github.com/DefinitelyTyped/DefinitelyTyped (which has a openApi type) 

A quicker option (as I really am limited in my time) is to make a flag to bypass spec validation. If will look into rebuilding in the new year
