### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jenaewhitmore** [Remco75/openapi-test-generator#6]
Upon using this for the first time to just test out I get the below error. Im using a prebuilt swagger spec just to test this framework out 
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json

I think it fails at constructing the OpenApiGenerator

![image](https://user-images.githubusercontent.com/14109666/39835435-2308812c-539e-11e8-8a6f-a10902d55c15.png)

M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

RangeError: Maximum call stack size exceeded
    at Object.fs.mkdirSync (fs.js:924:18)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:71:13)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:77:24)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)
    at sync (M:\Practice\JavaScript\NodejsConsoleApp1\node_modules\mkdirp\index.js:78:17)

**Comment by Remco75** [comment]
I will try to reproduce tomorrow, haven;t looked into this for a while. Will get back asap
